### ISSUE TITLE
This.currentTransaction turns to null after a POST request

### ISSUE THREAD

**Issue by rannygmx** [elastic/apm-agent-nodejs#515]
My application uses express to manage http requests.
I used the function setCustomContext in order to add a message to the log, and noticed that only in POST requests the message was not attached.
I started to debug my app and the module too, and i saw that after the request has been made it starts a transaction automatically and then goes to a function that called elasticAPMCallbackWrapper,  which occurs a lot of times, and at some point sets to this.currentTransaction null value.
As a result when i reached to setCustomContext function or any other function that requires open transaction (like buildSpan), the function is not performed because this.currentTransaction is null.

**Comment by watson** [comment]
Hi @rannygmx

Thanks for letting us know about this issue. The problem you're experiencing is most likely related to a context propagation issue. This happens when your application performs an async operation that we didn't anticipate. This is when a callback is scheduled to be called after some async operation finishes, but we fail to register it. If so, we don't know which transaction was the active transaction when the callback is finally called, and so `currentTransaction` is suddenly `null`.

90% of the time this is because of what's called a "user-land callback queue", where for instance a database-driver maintains an internal pool of connections to the databases. When you then make a database query, but all connections in the pool are in use, your query is put into a queue that waits until one of the connections in the pool becomes available. If the Node.js agent doesn't know about this pool, we'll also not know which transaction should be activated once the result of the query is returned.

Step one in figuring out what's going on in your particular case is to take a look at your dependencies. If you don't mind, could you please share with us the list of dependencies in your package.json file?

**Comment by watson** [comment]
Thanks for the update.

After looking though your dependencies, I think kafka-node is the culprit. There might be more modules breaking the context propagation, but kafka-node seems to be one of them.

The Kafka Node.js module uses a callback queue internally as can be seen here:
https://github.com/SOHU-Co/kafka-node/blob/572f51c362da11f6896116372b6466419b5a1e20/lib/client.js#L820-L832

To be certain, I need to make a test that replicates the problem. If the test shows kafka-node to break context propagation, the next step is to add official support for kafka-node in the agent.

**Comment by rannygmx** [comment]
Actually, my app doesn't require kafka-node, and I don't use kafka for http requests.

**Comment by watson** [comment]
Ah ok, thanks for letting me know.

I forgot you ask you before, but I assume you're running the latest version of the agent right? If not, please upgrade first and see if it goes away 😃 

Are you able to reproduce the problem in development? If so (or if you can do this in production), could I get you to [enable debug mode](https://www.elastic.co/guide/en/apm/agent/nodejs/current/troubleshooting.html#debug-mode) and post the resulting output log here showing your app starting up + both a GET request and a POST request being received and processed by the server. Be sure to redact any private or sensitive information before sharing the log file here.

**Comment by Qard** [comment]
The fact that this only occurs on POST requests leads me to believe you might be doing some sort of streaming to process the request body and that the context for that stream is not being bound, for whatever reason. We normally would bind it internally with the `bindEmitter` method of our `Instrumentation` class, which we do for http request and response objects automatically. If you have another stream in the pipeline there somewhere though, it's possible that context is getting lost there.

**Comment by rannygmx** [comment]
I reproduced the problem in development, 
There is the output in debug mode:
starting up:

`shimming Module._load function
shimming http@8.1.2 module
shimming http.Server.prototype.emit function 
shimming http.request function
shimming http.ServerResponse.prototype.writeHead function
shimming https@8.1.2 module
shimming https.Server.prototype.emit
shimming generic-pool@2.4.2 module
shimming generic-pool.Pool
shimming pg@6.0.4 module
shimming pg.Client.prototype.query
shimming redis@0.9.2 module
redis version 0.9.2 not supported - aborting...`

GET request:

`intercepted request event call to http.Server.prototype.emit 
{ id: '3062eb85-47e2-42a2-b171-980b8262b56f', 
result: 'success' } 
{ id: '3062eb85-47e2-42a2-b171-980b8262b56f', 
name: undefined, 
type: undefined } 
{ id: '3062eb85-47e2-42a2-b171-980b8262b56f' } 
intercepted call to http { id: '3062eb85-47e2-42a2-b171-980b8262b56f' } 
{ protocol: 'http:', 
host: '(censored)', 
id: '3062eb85-47e2-42a2-b171-980b8262b56f' } 
{ id: '3062eb85-47e2-42a2-b171-980b8262b56f', 
name: 'GET (censored)', 
type: 'ext.http.http' 
{ id: '3062eb85-47e2-42a2-b171-980b8262b56f' } 
{ id: '3062eb85-47e2-42a2-b171-980b8262b56f' } 
{ id: '3062eb85-47e2-42a2-b171-980b8262b56f', 
name: 'GET (censored)', 
type: 'ext.http.hftp', 
truncated: false } 
no active transaction found - cannot build new span 
intercepted call to http { id: null } 
no active transaction found - cannot build new span 
intercepted call to http { id: null } 
no active transaction found - cannot build new span 
intercepted call to http { id: null }setting default transaction name: GET /features/:id { id: '3062eb85-47e2-42a2-b171-980b8262b56f' } 
{ id: '3062eb85-47e2-42a2-b171-980b8262b56f' } 
setting timer to flush queue: 9883ms 
{ id: '3062eb85-47e2-42a2-b171-980b8262b56f', 
type: 'request', 
result: 'success', 
name: 'GET /features/:id' 
flushing queue 
sending transactions payload 
{ id: '3062eb85-47e2-42a2-b171-980b8262b56f' } 
intercepted call to http { id: null }transactions payload successfully sent`

POST request:

`intercepted request event call to http.Serverprototype.emit 
{ id: 'ac6d6fdf-dab6-49e7-8b44-f295e74ae330', 
result: 'success' } 
{ id: 'ac6d6fdf-dab6-49e7-8b44-f295e74ae330', 
name: undefined, 
type: undefined} 
{ id: 'ac6d6fdf-dab6-49e7-8b44-f295e74ae330'} 
intercepted call to http { id: 'ac6d6fdf-dab6-49e7-8b44-f295e74ae330' }{ protocol: 'http:', 
host: '(censored)', 
id: 'ac6d6fdf-dab6-49e7-8b44-f295e74ae330' }
{ id: 'ac6d6fdf-dab6-49e7-8b44-f295e74ae330', 
name: 'GET (censored)', 
type: 'ext.http.http' }
{ id: 'ac6d6fdf-dab6-49e7-8b44-f295e74ae330' } 
{ id: 'ac6d6fdf-dab6-49e7-8b44-f295e74ae330' } 
{ id: 'ac6d6fdf-dab6-49e7-8b44-f295e74ae330', 
name: 'GET (censored)', 
type: 'ext.http.http', 
truncated: false } 
no active transaction found - cannot build new span 
intercepted call to http { id: null } 
no active transaction found - cannot build new span 
intercepted call to http { id: null } 
no active transaction found - cannot build new span 
intercepted call to http { id: null } 
no active transaction found - cannot build new span 
intercepted call to http { id: null } 
no active transaction found - cannot build new span 
intercepted call to http { id: null } 
no active transaction found - cannot build new span 
intercepted call to http { id: null } 
no active transaction found - cannot build new span 
intercepted call to http { id: null } 
no active transaction found - cannot build new span 
intercepted call to http { id: null } 
no active transaction found - cannot build new span 
intercepted call to http { id: null } 
no active transaction found - cannot build new span 
intercepted call to http { id: null } setting default transaction name: POST /features/:id 
{ id: 'ac6d6fdf-dab6-49e7-8b44-f295e74ae330' }
{ id: tac6d6fdf-dab6-49e7-8b44-f295e74ae330' } 
setting timer to flush queue: 4948ms { id: 'ac6d6fdf-dab6-49e7-8b44-f295e74ae330', 
type: 'request', 
result: 'success', 
name: 'POST /features/:id' 
flushing queue 
sending transactions payload 
{ id: 'ac6d6fdf-dab6-49e7-8b44-f295e74ae330' } 
intercepted call to http { id: null }transactions payload successfully sent`

**Comment by watson** [comment]
I can see that you're using Node.js 8.1.2 in development. Are you also using this version in production?

I'm asking because we don't fully support Node.js 8.1.x as it contains a bug that have been fixed in 8.2.0, which means we can't fully instrument it. This might not be related to the bug you're experiencing, but I just want to make sure.

**Comment by watson** [comment]
Did that fix the issue?

Btw, unless you have specific reasons to run an older version of Node.js 8, I would recommend upgrading to the newest version (currently v8.11.4). It contains A LOT of performance improvements and bug fixes.

**Comment by rannygmx** [comment]
It didn't fix the issue.

But, in my POST request, I use `async.waterfall` and i noticed that when i make any async action in a waterfall the problem occurs, `currentTransaction` turns to null.

But when the action is out of the waterfall, or the waterfall has no any async action, it works.

**Comment by watson** [comment]
Thanks for the hint. I'll try and see if I can reproduce it using `async.waterfall` 👍

**Comment by Qard** [comment]
I did a quick test with `async.waterfall` and `setTimeout` tasks. The transaction was propagated appropriately. What async call did you use in the tasks that resulted in `currentTransation` becoming `null`?

**Comment by rannygmx** [comment]
I solved the problem!!

I found something more specific.
In my POST request I use the module `redis` for redis DB, redis keeps on an open connection and doing a TCP requests to get the data in it.
When Im getting the data in redis by using the `redis` module, the problem occurs.
After more tests, I figured out that the problem in the module, so I updated the module from `redis@0.9.2` to `redis@2.8.0` and now it works!

Thanks for the help! I hope that issue will help for more people.

**Comment by Qard** [comment]
Thanks for the update. I'm happy you figured it out. 😸

**Comment by watson** [comment]
@Qard maybe we should consider logging a warning if we detect that a version of a module is being used which is known to contain a user-land callback queue that we don't support (such as with Redis v0.9.2)?

**Comment by Qard** [comment]
Yeah, that's a good idea. Just a regular logger message that would be hidden at the default log level? Or should we complain more visibly? 🤔

**Comment by watson** [comment]
I would say on the `warning` level. That's not hidden by the default log level

**Comment by coolboi567** [comment]
Similar issue here.

**The following error is showing up very often:**
```
no active transaction found - cannot build new span
intercepted call to http.request %o { id: null }
```
**And, once in a while:**
```
intercepted request event call to http.Server.prototype.emit
Elastic APM caught unhandled exception: crypto.randomFillSync is not a function
Sending error to Elastic APM { id: '2e574bc2a5005713d9170fb2a8f0cec8' }
```
**Also, few times:**
```
intercepted request event call to http.Server.prototype.emit
Elastic APM caught unhandled exception: crypto.randomFillSync is not a function
Sending error to Elastic APM { id: '3ea782c0be23f393153d7cd05823e465' }
```

**Environment :** 
OS: Ubuntu 14.04.4 LTS - trusty
node version: v6.11.4
npm: v6.4.1

**Other dependencies :**
ioredis version: v2.5.0
redis-parser: v1.3.0

**Comment by watson** [comment]
@coolboi567 I think this is unrelated. I've created a separate issue for this bug: #701

I'm working on fixing it right now. Expect a new release of the agent later today with a fix for it.
